# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

# Your name, as you want it to appear underneath each post and in the footer
author: luc demortier
simple_search: http://google.com/search

# This is the default title that shows up on the browser tab of each page.
title: Light on Data
subtitle: Content-centric blogging
# Short description (goes below the title; it will also be used in the RSS feed)
description: A blog by a physicist turned data scientist
# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Light On Data

# Turn on recognition of Github Flavored Markdown
markdown: Kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
external_link: true

permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']

post:
  template: _post.txt
  extension: md

page:
  template: _page.txt
  extension: md

collections:
  projects:
    output: true
  papers:
    output: true

editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
